### ISSUE TITLE
About metrics

### ISSUE THREAD

**Issue by nlgandnlu** [less-and-less-bugs/Trust_TELLER#2]
Thank you very much for your excellent work and open-source code. I would like to ask if it is possible to obtain more evaluation metrics such as micro-f1, precision, recall, etc. for the methods in the paper table 2, so that the data can be more abundant when citing your research results. What should I do if possible? Thanks again！

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added new functions to calculate micro-f1, precision, and recall metrics. Updated the existing calculate_macro_f1 function to return more metrics. These changes will provide more comprehensive evaluation metrics as requested in the GitHub issue.

You can review changes in this commit: https://github.com/mnmnk43434/less-and-less-bugs-Trust_TELLER-2/commit/0d6c19de36f3f55c9d0561cd8fe8eb46678ecba9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by less-and-less-bugs** [comment]
I will check tomorrow.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Haitao Bai ***@***.***>
发送时间: Monday, December 2, 2024 9:45:13 PM
收件人: less-and-less-bugs/Trust_TELLER ***@***.***>
抄送: Subscribed ***@***.***>
主题: [less-and-less-bugs/Trust_TELLER] About metrics (Issue #2)


Thank you very much for your excellent work and open-source code. I would like to ask if it is possible to obtain more evaluation metrics such as micro-f1, precision, recall, etc. for the methods in the paper table 2, so that the data can be more abundant when citing your research results. What should I do if possible? Thanks again！

―

**Comment by less-and-less-bugs** [comment]
Thank you very much for your attention! In camera-ready version https://aclanthology.org/2024.findings-acl.919.pdf, we provide such statistics in Table 17 for one dataset. For other datasets, you have to re-run our codes (all data and code has been provided). Thank you again.
